### PR TITLE
Use --appimage-extract rather than unappimage

### PR DESCRIPTION
**Pull request by orowith2os**

### CODE REVIEW

**Comment by orowith2os** [comment]
I accidentally mistyped a command to build it, should be working now.

**Comment by orowith2os** [comment]
bot, build org.jitsi.jitsi-meet

**Comment by orowith2os** [comment]
bot, build org.jitsi.jitsi-meet

**Comment by ananace** [comment]
If you're going to remove it, just remove it, commenting out when working with a version control system isn't helpful

**Comment by orowith2os** [comment]
I kept it just in case it was needed in the future, but I'll remove it entirely if you say so.

**Pull request merged**
